// endpoints.ts
export const ENDPOINTS = {
    AUDITLOGS: '/auditLogs',
    APP_ACTIVITY: '/app-activity',
    BLOGS: '/blogs',
    ARTICLES: '/articles',
    ALERTS: '/alerts',
    BOOKMARKS: '/bookmarks',
    CAROUSELS: '/carousels',
    COURSES: '/courses',
    PHONE_TYPES: '/phone-types',
    ADDRESS_TYPES: '/address-types',
    EMAIL_ADDRESS_TYPES: '/email-address-types',
    STATES: '/states',
    GENDERS: '/genders',
    TIMEZONES: '/timezones',
    CATEGORIES: '/categories',
    COMMUNICATIONS: '/communications',
    FEATURETTES: '/featurettes',
    PARALLAXS: '/parallaxs',
    PROFILE_TYPES: '/profile-types',
    PRODUCT_TYPES: '/product-types',
    STATUS: '/status',
    FAVORITES: '/favorites',
    SERVICE_BOXES: '/service-boxes',
    CONTACTS: '/contacts',
    DOCUMENTS: '/uploads',
    DROPDOWNS: '/dropdowns',
    EMAILS: '/emails',
    HELP: '/help',
    QUOTES: '/quotes',
    HELP_PROGRESS: '/help-progress',
    PROPERTIES: '/properties',
    GROUPS: '/groups',
    POSTS: 'posts',
    MESSAGES: '/messages',
    OPPORTUNITES: '/opportunities',
    ADDRESSES: '/addresses',
    PHONE_NUMBERS: '/phone-numbers',
    EMAIL_ADDRESSES: '/email-addresses',
    FOPS: '/fops',
    IMAGES: '/images',
    JUST_TEXTS: '/just-texts',
    PROJECTS: '/projects',
    AFFECTED_PARTIES: '/affected-parties',
    AFFECTED_SYSTEMS: '/affected-systems',
    APPROVALS: '/approvals',
    BUGS: '/bugs',
    DELIVERABLES: '/deliverables',
    IMPLEMENTATION_PLANS: '/implementation-plans',
    REQUIREMENTS: '/requirements',
    NEWS: "/news",
    EVENTS: '/events',
    SETTINGS: '/settings',
    STORES: '/stores',
    STATS: '/stats',
    PRODUCT_BUNDLES: '/product-bundles',
    SHOPPING_CARTS: '/shopping-carts',
    CATALOGS: '/catalogs',
    INVOICES: '/invoices',
    ORDERS: '/orders',
    OFFERS: '/offers',
    PAYMENTS: '/payments',
    PRODUCTS: '/products',
    RECEIPTS: '/receipts',
    USERS: '/users',
    TASKS: '/tasks',
    TOPICS: '/topics',
    GOALS: '/goals',
    PROJECT_REPORTS: '/project-reports',
    WORK_FLOWS: '/work-flows',
    ACTION_FLOWS: '/actions',
} as const;

export const DROPDOWN_ENDPOINTS = ['CATEGORIES', 'STATES', 'STATUS', 'PROFILE_TYPES', 'PRODUCT_TYPES', 'PHONE_TYPES', 'ADDRESS_TYPES', 'EMAIL_ADDRESS_TYPES', 'GENDERS', 'TIMEZONES'] as const;

export type EndpointKeys = keyof typeof ENDPOINTS;
export type DropdownEndpointKeys = typeof DROPDOWN_ENDPOINTS[number];
